export type ReservationStatus =
  | "RECIBIDA"
  | "PENDIENTE_VALIDACION"
  | "CONFIRMADA"
  | "CONFIRMADA_TRAS_VALIDACION"
  | "RECHAZADA_CONFLICTO"
  | "RECHAZADA_REGLA_HORARIO"
  | "RECHAZADA_MIN_ANTICIPACION"
  | "RECHAZADA_POR_RESPONSABLE"
  | "CANCELADA"
  | "ERROR_CALENDAR";
